- hosts: webservers
  become: true
  vars:
   appname: nginx
   appstatus: present
   packagestatus: yes

  tasks:
  - name: Update and upgrade apt packages
    apt: 
      upgrade: "{{packagestatus}}"
      update_cache: "{{packagestatus}}"
      #cache_valid_time: 86400 
  - name: installing "{{appname}}" software
    apt:
      name: "{{appname}}"
      state: "{{appstatus}}"

  - name: begin "{{appname}}" service
    service:
      name: "{{appname}}"
      state: started